image: marioarduini/rumble-source:2020-11-13

build-rumble:
  stage: build
  script:
    - ant -buildfile build_antlr_parser.xml generate-parser -Dantlr.jar=lib/antlr-4.7-complete.jar
    - mvn clean compile assembly:single

frontend-test:
  stage: test
  script:
    - mvn -Dtest=FrontendTests test
    
runtime-test:
  stage: test
  script:
    - mvn -Dtest=RuntimeTests test

sparkruntime-test:
  stage: test
  script:
    - mvn -Dtest=SparkRuntimeTests test

javaapi-test:
  stage: test
  script:
    - mvn -Dtest=JavaAPITest test

spotless-test:
  stage: test
  script:
    - mvn spotless:check

