site_name: Rumble 1.11 "Banyan Tree" beta
pages:
  - '1. Documentation home': 'index.md'
  - '2. Getting started': 'Getting started.md'
  - '3. Run on a cluster': 'Run on a cluster.md'
  - '4. Run in Jupyter notebooks (experimental)': 'HTTPServer.md'
  - '5. The JSONiq language': 'JSONiq.md'
  - '6. Reading data': 'Input.md'
  - '7. Function library': 'Function library.md'
  - '8. CLI and HTTP parameters': 'CLI.md'
  - '9. Machine learning library': 'RumbleML.md'
  - '10. Error codes': 'Error codes.md'
  - '11. Compile from GitHub': 'install.md'
  - '12. Licenses': 'Licenses.md'
theme: readthedocs
